name: Create a report
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      suffix:
        type: string
        default: ""
      file_name:
        type: string
        default: "data"
      folder:
        type: string
        default: "data"
      email:
        type: string
        default: "karunakar.antham@seb.se"

jobs:
  auditreport:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print the input tag to STDOUT
        run: |
          echo  ${{github.event_name}}
          echo  The tags are "${{github.events.inputs.file_name}}"
          echo  The suffix is "${{inputs.suffix}}"
          echo  The file_name is "${{inputs.file_name}}"
          echo  The folder is ${{inputs.folder}}

      # - name: Checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Format report
        run: |
          echo "Creating audit report... with download"
          git log -c --pretty=###%H»¦«%aN»¦«%aD»¦«%s.%b $GITHUB_WORKSPACE/${{inputs.folder}}/prod/${{inputs.file_name}}${{inputs.suffix}}.csv | awk -f $GITHUB_WORKSPACE/src/preFormat.awk > TxWhitelistAuditReport${{inputs.suffix}}.csv
      - name: update Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: csv-audit-report
          path: TxWhitelistAuditReport${{inputs.suffix}}.csv
